platform :ios, '9.0'

target 'CommonKit' do
use_frameworks!

pod 'XMNetworking', '~> 1.0.2'

pod 'MJRefresh', '~> 3.1.15.3'
pod 'SDAutoLayout', '~> 2.2.0'

#pod 'YYCategories'
#pod 'YYCache'
#pod 'YYModel'
#pod 'YYImage'
pod 'YYKit'
end
